pool:
  vmImage: 'windows-latest'
 

variables:
  major: 2
  minor: 0
  build: $[counter(format('{0}.{1}',variables['major'],variables['minor']), 0)]

name: $(major).$(minor).$(build).0 - $(Date:yyyy.MM.dd)

steps:
- task: NodeTool@0
  displayName: Install Node.js
  inputs:
    versionSpec: 16.x
    checkLatest: true
- task: UseDotNet@2
  displayName: Install .NET 6.0
  inputs:
    packageType: sdk
    version: 6.0.x
- task: DotNetCoreCLI@2
  displayName: Restore packages
  inputs:
    command: restore
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Build website
  inputs:
    command: publish
    projects: '**/Hechinger.FSK.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory) -p:VersionPrefix=$(major).$(minor).$(build) -p:InformationalVersion="$(Build.BuildNumber)"'
    publishWebProjects: true
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: Publish ZIP files
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'FSK'
